graph TD
    A(("Начало"))
    B[/"points: List<DataPoint>, x0: Double"/]
    C["val n = points.size\nval table = InterpolationLogicController.buildFiniteDifferenceTable(points)\nval h = points[1].x - points[0].x\nval t = (x0 - points[0].x) / h\nvar result = table.differences[0][0]\nvar mult = 1.0" ]
    D{"for (i in 1 until n)"}
    E["mult *= (t - (i - 1))"]
    F["result += table.differences[0][i] / InterpolationLogicController.factorial(i) * mult"]
    I[Pair &lt;Double, String&gt; ]
    J(("Конец"))

    A --> B --> C --> D
    D -- Да --> E --> F --> D
    D -- Нет --> I --> J 